### ISSUE TITLE
Create account implementation contract

### ISSUE THREAD

**Issue by Darlington02** [Starknet-Africa-Edu/TBA#2]
Account implementation to be deployed for a TBA.
TODOs
1. Account Interface should subscribe to Argent account implementation and ERC6551. should contain `token` (which returns the NFT contract address and tokenId), and `owner` (which returns owner of NFT).
2. Account needs to be upgradeable, and thus should implement the `replace_class_syscall`
3. `__execute__` should check that caller is NFT owner

**Comment by codeWhizperer** [comment]
I will work on this.
