### ISSUE TITLE
Registry frontend

### ISSUE THREAD

**Issue by Darlington02** [Starknet-Africa-Edu/TBA#3]
A frontend UI which can be interacted with to deploy a TBA. UI should be neat and detailed, as project plans to be scaled.

TODOs
1. Registry should have a simple form to take in the address of the implementation contract, NFT contract address, and NFT token ID.
2. The `public_key` and `salt` will be randomly generated. Please take a look at the starknetjs docs for reference.
3. Call the `create_account` function with all the necessary inputs with a click of a button

**Comment by codeWhizperer** [comment]
setting up the repo
