### ISSUE TITLE
upgrade contracts to cairo v2.6.0

### ISSUE THREAD

**Issue by Darlington02** [Starknet-Africa-Edu/TBA#37]
- upgrade contracts to cairo v2.6.0

**Comment by TeddyNotBear** [comment]
May I take it ?

**Comment by Darlington02** [comment]
Hey @TeddyNotBear sure, you can. Add the declared classhashes and deployed contracts here:

https://github.com/Starknet-Africa-Edu/TBA/blob/main/addresses.txt
