### ISSUE TITLE
migrate project from Scarb to Starknet Foundry

### ISSUE THREAD

**Issue by Darlington02** [Starknet-Africa-Edu/TBA#4]
TODO:
Migrate entire project to use Starknet Foundry instead, to ensure we don't face hiccups with running integration tests as we go forward:)

**Comment by codeWhizperer** [comment]
I will work on this

**Comment by Darlington02** [comment]
Yeap, and that’s why I might have to do it myself, since I’d be working on establishing the project structure🙏
